#!/usr/bin/env python
#_*_coding:utf8_*_



f = file('stu_list.txt')
stu_dic={}

for id,line in enumerate(f):
        stu_dic[id] = line.strip()

def add_user():
    user = raw_input("User:")
    #if search_info(user)
    tel = raw_input('Tel Phone:')
    compate = raw_input('Compane:')
    email = raw_input('email:')
def del_user():
    user = raw_input("Please input the user:")

def update_info():
    print "change"

def check_user():
   if search_info():
       print "username exsit!"   

def search_info():
    choice = raw_input('Search info:')
    while True:
        mathc_list = {}
        if choice == 'exit':break
        if stu_dic.has_key(choice):
            mathc_list[choice] = stu_dic.get(choice)
            print mathc_list
        choice = str(choice)

        if len(choice) >= 3:
            for id,val in stu_dic.items():
                if str(choice) in val:
                    mathc_list[id] =val
        for k,v in mathc_list.items():
            print k,v
            pass

check_user()
